name: java execution

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: openjdk:17-jdk-slim

    steps:
    - uses: actions/checkout@v4
    - name: Compile Java file
      run: javac Hello.java
    - name: Run Java Program
      run: java Hello
